config/routes.rb
Rails.application.routes.draw do

  root :to => "homes#top"

  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  delete 'logout' => "sessions#destroy"

  resources :users, only: [:new, :create, :index, :edit, :update]

  resources :spots, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :spot_comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :user
  belongs_to :spot
  
end

app/models/spot.rb
class Spot < ApplicationRecord
  
  belongs_to :user
  has_many :spot_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  has_one_attached :image_id
  
  validates :title, presence: true
  validates :body, presence: true
  validates :lat, presence: true
  validates :lng, presence: true
  
  def get_image_id
    (image_id.attached?) ? image_id : 'no_image.jpg'
  end
  
  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end
  
end

app/models/spot_comment.rb
class SpotComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :spot
  
end

app/models/user.rb
class User < ApplicationRecord
    
    has_many :spot_comments, dependent: :destroy
    has_many :spots, dependent: :destroy
    has_many :likes, dependent: :destroy
    
    has_secure_password #dbに依存せずpass+confirmpass使用可能に(Gem'bcrypt'で使用できるようになっている)

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :current_user
  helper_method :signin_user?
  helper_method :admin?

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) #自己代入
  end

  def signin_user?
    if @current_user == nil
      redirect_to root_path
      ccc
    end
  end

  def admin?
    if @current_user.admin == false
      redirect_to request.referer
    end
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def create
    spot = Spot.find(params[:spot_id])
    like = @current_user.likes.new(spot_id: spot.id)
    like.save
    redirect_to spot_path(spot)
  end
  
  def destroy
    spot = Spot.find(params[:spot_id])
    like = @current_user.likes.find_by(spot_id: spot.id)
    like.destroy
    redirect_to request.referer
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    @user = User.find_by(name: session_params[:name]) #name入力値から既存nameを検索
    if @user&.authenticate(session_params[:password]) #該当name発見時、メソッドauthenticateでpassと整合性確認
      session[:user_id] = @user.id #ログイン成功時ログイン状態保持する為sessionでuser_idを保持させる
      redirect_to spots_path
    else
      redirect_to request.referer
      flash[:alert] = "ログインできません。"
    end
  end

  def destroy
    if session.delete(:user_id)
      @current_user = nil #sessionのuse_id削除、メソッドcurrent_user=nillでログアウト状態を作る
      redirect_to root_path
      flash[:alert] = "ログアウトしました。"
    else
      redirect_to spots_path
      flash[:alert] = "ログアウト出来ませんでした。"
    end
  end

  private

  def session_params
    params.require(:session).permit(:name, :password, :user_id)
  end

end

app/controllers/spot_comments_controller.rb
class SpotCommentsController < ApplicationController
  
  def create
    spot = Spot.find(params[:spot_id])
    comment = @current_user.spot_comments.new(spot_comment_params)
    comment.spot_id = spot.id
    if comment.save
      redirect_to request.referer
    else
      redirect_to request.referer
      flash[:alert] = "コメント出来ませんでした。"
    end
  end
  
  def destroy
    if SpotComment.find_by(id: params[:id], spot_id: params[:spot_id]).destroy
      redirect_to request.referer
    else
      redirect_to request.referer
      flash[:alert] = "投稿出来ませんでした。"
    end
  end
  
  private
  
  def spot_comment_params
    params.require(:spot_comment).permit(:comment)
  end
  
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController

  before_action :signin_user?

  def new
    @user = @current_user
    @spot = Spot.new
  end

  def create
    @spot = Spot.new(spot_params)
    @user = @current_user
    @spot.user_id = @user.id
    if @spot.lat ==0 || @spot.lng == 0 #この場合は場所指定忘れの可能性高い為入力不可とする
      redirect_to request.referer
      flash[:alert] = "投稿出来ませんでした。"
    elsif @spot.save
      redirect_to spots_path
    else
      redirect_to request.referer
      flash[:alert] = "投稿出来ませんでした。"
    end
  end

  def index
    @spots = Spot.all
    @spotlank = Spot.all
  end

  def show
    @spot = Spot.find(params[:id])
    @spot_comment = SpotComment.new
  end

  def edit
    spot_editer?
    @spot = Spot.find(params[:id])
  end

  def update
    @spot = Spot.find(params[:id])
    if @spot.update(spot_params)
      redirect_to spot_path(@spot)
    else
      request.referer
      flash[:alert] = "更新出来ませんでした。"
    end
  end

  def destroy
    @spot = Spot.find(params[:id])
    if @spot.destroy
      redirect_to spots_path
    else
      redirect_to request.referer
      flash[:alert] = "削除出来ませんでした。"
    end
  end


  private

  def spot_editer?
    @spot = Spot.find(params[:id])
    unless @current_user.id == @spot.user.id || @current_user.name == "admin"
      redirect_to root_path
      flash[:alert] = "権限がありません。"
    end
  end

  def spot_params
    params.required(:spot).permit(:user_id, :title, :body, :lat, :lng, :image_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signin_user? , except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to spots_path
    else
      redirect_to request.referer
      flash[:alert] = "登録出来ません。もう一度お願い致します。"
    end
  end

  def index
    @users = User.all
  end

  def edit
    editer?
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to edit_user_path(@user)
      flash[:alert] = "更新しました。"
    else
      redirect_to request.referer
      flash[:alert] = "更新出来ませんでした。"
    end
  end

  private
  
  def editer?
    @user = User.find(params[:id])
    unless @current_user.id == @user.id || @current_user.name == "admin"
      redirect_to root_path
      flash[:alert] = "権限がありません。"
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/spot_comments_helper.rb
module SpotCommentsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class = "top container">
  <div class = "top-title">
    Let's!<br>
  La <% if @current_user == nil %>
      <%= link_to login_path do %><i class="fas fa-car-side" style="color: red;"></i><% end %>-☆
    <% else %>
      <%= link_to spots_path do %><i class="fas fa-car-side" style="color: red;"></i><% end %>-☆
    <% end %>
  </div>
</div>

app/views/layouts/_header_on.html.erb
<div class="hamburger">
  <span></span>
  <span></span>
  <span></span>
</div>

<nav class="globalMenuSp">
    <ul>
        <li><%= link_to "Top", root_path %></li>
        <li><%= link_to "スポット一覧/ナビ", spots_path %></li>
        <li><%= link_to "スポット投稿", new_spot_path %></li>
        <li><%= link_to "マイページ", edit_user_path(@current_user) %></li>
        <% if @current_user.name == "admin" %>
            <li><%= link_to "会員一覧", users_path %></li>
        <% end %>
        <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
    </ul>
</nav>

app/views/layouts/_header_yet.html.erb
<div class="hamburger">
  <span></span>
  <span></span>
  <span></span>
</div>

<nav class="globalMenuSp">
    <ul>
      <li><%= link_to "Top", root_path %></li>
      <li><%= link_to "ログイン", login_path %></li>
      <li><%= link_to "新規登録", new_user_path %></li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LetsLa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= alert %>
    <% if @current_user == nil %>
      <%= render 'layouts/header_yet' %>
    <% else %>
      <%= render 'layouts/header_on' %>
    <% end %>
    <%= yield %>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['MAP_KEY'] %>&callback=initMap"></script>
  </body>
</html>

<script> //ヘッダー用jsまとめて記述
  $(function() {
    $('.hamburger').click(function() {
        $(this).toggleClass('active');

        if ($(this).hasClass('active')) {
            $('.globalMenuSp').addClass('active');
        } else {
            $('.globalMenuSp').removeClass('active');
        }
    });
});
</script>

app/views/spots/edit.html.erb
<div class="show-container container">
  <%= form_with model: @spot, method: :patch do |f| %>
  <div class="spot-title row">
    <h2 class="font-weight-bolder"><%= @spot.title %></h2>
  </div>
  <div class="show-row row col-12 d-flex justify-content-between">
    <div class="post-left">
      <div id='map'></div>
      <input id="address" type="textbox" value="<%= @spot.title %>">
      <input type="button" value="検索" onclick="codeAddress()">
    </div>
    <div class="edit-right">
      <h4>画像</h4>
      <%= f.file_field :image_id, accept: "image/*" %>
      <h4>タイトル</h4>
      <%= f.text_field :title %>
      <h4>詳細</h4>
      <%= f.text_area :body %>
      <%= f.hidden_field :lat,:value => @spot.lat, id: :lat %>
      <%= f.hidden_field :lng,:value => @spot.lng, id: :lng %>
    </div>
  </div>
  <div class="row">
    <div class="btn-spotedit">
      <%= f.submit '編集', class: 'btn btn-success' %>
    </div>
  </div>
  <% end %>
</div>

<style>
  #map {
    height: 50vh;
    width: 50vh;
  }
</style>

<script>
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()
  map = new google.maps.Map(document.getElementById('map'), {
      center:  {lat: <%= @spot.lat %>, lng: <%= @spot.lng %>},  //東京
      zoom: 15,
    });
  let transitLayer = new google.maps.TransitLayer();
  transitLayer.setMap(map);
    ( function() {
      let markerLatLng = new google.maps.LatLng({lat: <%= @spot.lat %>, lng: <%= @spot.lng %>});
      let marker = new google.maps.Marker({
        position: markerLatLng,
        map: map
      });
      let infowindow = new google.maps.InfoWindow({
        position: markerLatLng,
        content: "<a><%= @spot.title %></a>"
      }); 
      marker.addListener('click', function() {
        infowindow.open(map, marker);
      });
   })();
}

let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      if (aft == true){
          marker.setMap(null);
      }
      map.setCenter(results[0].geometry.location);
          marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location,
          draggable: true
      });
      aft = true
      document.getElementById('lat').value = results[0].geometry.location.lat();
      document.getElementById('lng').value = results[0].geometry.location.lng();
      google.maps.event.addListener( marker, 'dragend', function(ev){
          document.getElementById('lat').value = ev.latLng.lat();
          document.getElementById('lng').value = ev.latLng.lng();
      });
      } else {
        alert('該当する結果がありませんでした：' + status);
      }
    });
  }
</script>

app/views/spots/index.html.erb
<div class="indexcont container">
  <div class="map-box">
    <div id='map'></div>
  </div>
  <div class="nav-box d-flex justify-content-between">
    <div class="select-form">
      既存スポットから検索!<br>
      <select id="start">
      <% @spots.each do |spot| %>
        <option value="<%= spot.lat %>,<%= spot.lng %>"><%= spot.title %></option>
      <% end %>
      </select><br>
      ↓<br>
      <select id="end">
        <% @spots.each do |spot| %>
          <option value="<%= spot.lat %>,<%= spot.lng %>"><%= spot.title %></option>
        <% end %>
      </select><br>
      <select id="reset">
        <option value="leave">残す</option>
        <option value="delete">消す</option>
      </select>
      <input type="submit" id="btn" value="検索" onclick="selectNav()">
    </div>
    <div class="search-form">
      入力して検索!<br>
      <input type="textbox" id="go" value="" placeholder="名前or緯度,経度で検索"><br>
      ↓<br>
      <input type="textbox" id="fin" value="" placeholder="名前or緯度,経度で検索"><br>
      <select id="testreset">
        <option value="leave">残す</option>
        <option value="delete">消す</option>
      </select>
    <input type="button" id="btn" value="ナビ" onclick="searchNav()">
    </div>
  </div>
</div>

<style>
  #map {
    height: 70vh;
    width: 130vh;
  }
</style>

<script>
  let map
  let marker

  function initMap(){
    geocoder = new google.maps.Geocoder()
    map = new google.maps.Map(document.getElementById('map'), {
        center:  {lat: 36.31616117084595, lng: 140.0458184125},  //中心用
        zoom: 4.6, //日本全体用
        mayTypeId: google.maps.MapTypeId.ROADMAP
      });

    <% @spots.each do |spot|%>
      ( function() {
        let markerLatLng = new google.maps.LatLng({lat: <%= spot.lat %>, lng: <%= spot.lng %>});
        let marker = new google.maps.Marker({
          position: markerLatLng,
          map: map,
          animation: google.maps.Animation.BOUNCE
        });
        let infowindow = new google.maps.InfoWindow({
          position: markerLatLng,
          content:
              "<a href='<%= spot_path(spot) %>' ><%= spot.title %></a>" +
              "(緯度,経度)=(<%= spot.lat %>,<%= spot.lng %>)"
            });
        marker.addListener('click', function() {
          infowindow.open(map, marker);
          });
      })();
     <% end %>
  }

    // 検索用
    function searchNav(){
    let renav = document.getElementById('testreset').value;
    let inputstart = document.getElementById('go').value;
    let inputend = document.getElementById('fin').value;
      if (renav == "delete"){
        initMap(map);　//前の情報が残らない様に一度初期化
      }
    let directionsService = new google.maps.DirectionsService;
    let directionsRenderer = new google.maps.DirectionsRenderer;
    directionsService.route({
      origin: inputstart, //スタート地点
      destination: inputend,　//ゴール地点
      travelMode: google.maps.TravelMode.DRIVING,　//電車・徒歩ver対応しない為自動車に限定
      avoidHighways: true, //高速禁止
      avoidTolls: true //有料区間禁止(上記と併せて徒歩でも行けるようなルートにする)
    }, function(response, status) {
        console.log(response);
        if (status === google.maps.DirectionsStatus.OK) {
          directionsRenderer.setMap(map);
          directionsRenderer.setDirections(response);
          directionsRenderer.setOptions({
            polylineOptions: {
                strokeColor: '#f246c5',
                strokeOpacity: 0.8,
                strokeWeight: 8
            }
          });
          alert("ルート検出！")
          }else{
            alert("すみません、検索出来ません")
          }
      });
  }

  // セレクト用
  function selectNav(){
    let renav = document.getElementById('reset').value;
    let inputstart = document.getElementById('start').value;
    let inputend = document.getElementById('end').value;
      if (renav == "delete"){
        initMap(map);
      }
    let directionsService = new google.maps.DirectionsService;
    let directionsRenderer = new google.maps.DirectionsRenderer;
    directionsService.route({
      origin: inputstart,
      destination: inputend,
      travelMode: google.maps.TravelMode.DRIVING,
      avoidHighways: true,
      avoidTolls: true
    }, function(response, status) {
        console.log(response);
        if (status === google.maps.DirectionsStatus.OK) {
          directionsRenderer.setMap(map);
          directionsRenderer.setDirections(response);
          directionsRenderer.setOptions({
            polylineOptions: {
                strokeColor: '#f246c5',
                strokeOpacity: 0.8,
                strokeWeight: 8
            }
          });
          alert("ルート検出！")
        }else{
          alert("すみません、検索出来ません")
        }
      });
  }
</script>

app/views/spots/new.html.erb
<div class ="container text-center">
  <%= form_with model: Spot.new do |f| %>
  <div class ="spot-title row">
  <h2 class="font-weight-bolder">スポット投稿</h2>
    <div class="row justify-content-center mt-2">
      <div class="post-left">
        <div id='map'></div>
        <div class="spotinfo mt-3">
          <input id="address" type="textbox" placeholder="スポットを入力!">
          <input type="button" value="検索" onclick="codeAddress()">
          <%= f.hidden_field :lat,:value =>"緯度", id: :lat %>
          <%= f.hidden_field :lng,:value =>"経度", id: :lng %>
        </div>
      </div>
      <div class="newspot-form col-6 mt-3 pl-5">
        <h4>画像</h4>
        <%= f.file_field :image_id, accept: "image/*" %>
        <h4>タイトル</h4>
        <%= f.text_field :title %>
        <h4>詳細</h4>
        <%= f.text_area :body %>
      </div>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-12 mb-2">
      <%= f.submit '投稿', class: 'btn btn-primary' %>
    </div>
  </div>
  <% end %>
</div>

<style>
  #map {
    height: 55vh;
    width: 55vh;
  }
</style>

<script>
// セット(初期マップ定義)
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()
  map = new google.maps.Map(document.getElementById('map'), {
      center:  {lat: 35.6803997, lng:139.7690174},  //東京
      zoom: 15,
    });
  }
//検索
let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
        if (aft == true){
            marker.setMap(null);
        }
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true
        });
        aft = true
        document.getElementById('lat').value = results[0].geometry.location.lat();
        document.getElementById('lng').value = results[0].geometry.location.lng();
        //ドラッグ時緯度経度変更アクション
        google.maps.event.addListener( marker, 'dragend', function(ev){
            document.getElementById('lat').value = ev.latLng.lat();
            document.getElementById('lng').value = ev.latLng.lng();
        });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });
}
</script>

app/views/spots/show.html.erb
<div class="show-container container">
  <div class="spot-title row">
    <h2 class="font-weight-bolder"><%= @spot.title %></h2>
  </div>
  <div class="show-row row col-12 d-flex justify-content-between">
    <div class="post-left">
      <div id='map'></div>
    </div>
    <div class="show-right">
      <div class="show-img text-center">
      <%= image_tag @spot.get_image_id, class:'card-img-show' %>
      </div>
      <div class="show-body text-center">
        <%= @spot.body %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="comment d-flex justify-content-between">
      <ul class="spot-comment">
          <% @spot.spot_comments.each do |spot_comment| %>
            <li>
              <%= spot_comment.comment %><br>
              <div class="text-right mr-2">
                <%= spot_comment.created_at.strftime('%Y/%m/%d') %>
                by <%= spot_comment.user.name %>
                <% if @spot_comment.user == @current_user || @current_user.name == "admin"  %>
                  <%= link_to "削除", spot_spot_comment_path(spot_comment.spot, spot_comment), method: :delete %>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
    </div>
    <div class="comment-right text-center">
      <div class="like">
        <% if @spot.liked_by?(@current_user) %>
          <%= link_to spot_likes_path(@spot), method: :delete do %>
          <%= @spot.likes.count %><i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
        <% end %>
        <% else %>
          <%= link_to spot_likes_path(@spot), method: :post do %>
            <%= @spot.likes.count %><i class="fas fa-heart" aria-hidden="true"></i>
          <% end %>
        <% end %>
      </div>
      <div class="comment-form">
        <%= form_with model: [@spot, @spot_comment] do |f| %>
          <%= f.text_area :comment, placeholder: "コメントを入力してください" %><br>
          <%= button_tag(type: "submit", class: 'btn comment-btn') do %>
            <i class="fas fa-comment" style="color: #d879ac;"></i>
          <% end %>
        <% end %>
      </div>
      <div class="spot-edit">
        <% if @spot.user == @current_user || @current_user.name == "admin"  %>
          <%= link_to "編集", edit_spot_path(@spot), class: 'btn btn-success' %>
          <%= link_to "削除", spot_path(@spot), method: :delete, class: 'btn btn-danger' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<style>
  #map {
    height: 45vh;
    width: 45vh;
  }
</style>

<script>
function initMap() {
  let latlng = new google.maps.LatLng(<%= @spot.lat %>, <%= @spot.lng %>);
  let styles = [
     {
      stylers: [
       { "saturation": 0 },
       { "lightness": 0 }
      ]
     }
    ];
  let map = new google.maps.Map(document.getElementById('map'), {
    zoom: 15,
    styles: styles,
    center: latlng
  });
  let transitLayer = new google.maps.TransitLayer();
  transitLayer.setMap(map);
    ( function() {
      let markerLatLng = new google.maps.LatLng({lat: <%= @spot.lat %>, lng: <%= @spot.lng %>});
      let marker = new google.maps.Marker({
        position: markerLatLng,
        map: map
      });
      let infowindow = new google.maps.InfoWindow({
        position: markerLatLng,
        content: "<a><%= @spot.title %></a>"
      }); 
      marker.addListener('click', function() {
        infowindow.open(map, marker);
      });
   })();
}
</script>

app/views/users/edit.html.erb
<div class="container">
  <div class="registrations-form">
    <h1>会員情報編集</h1>
    <%= form_with model: @user, method: :patch do |f| %>
      <div class="field">
        <%= f.label "ユーザーネーム" %><br>
        <%= f.text_field :name%>
      </div>
      <div class="field">
        <%= f.label "メールアドレス" %><br>
        <%= f.text_field :email, class:"col-7" %>
      </div>
      <div class="registrations-btn">
        <%= f.submit "変更", class:"btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center font-weight-bolder">ユーザー一覧</h1>
  </div>
</div>
<div class="row">
  <div class="col-10 offset-1">
    <table class="table">
      <thead>
        <tr class="table-secondary">
          <th>ユーザーID</th>
          <th>ユーザーネーム</th>
          <th>メールアドレス</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><u><%= link_to user.name, edit_user_path(user), class: "text-dark" %></u></td>
          <td><%= user.email %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="registrations-form">
    <h1>新規登録</h1>
    <%= form_with model: @user, url: users_path, local: true do |f| %>
    <div class="field">
      <%= f.label "ユーザーネーム" %><br>
      <%= f.text_field :name %>
    </div>
    
    <div class="field">
      <%= f.label "メールアドレス" %><br>
      <%= f.text_field :email %>
    </div>
    
    <div class="field">
      <%= f.label :password %><br>
      <%= f.text_field :password %>
    </div>
    
    <div class="field">
      <%= f.label "確認用password" %><br>
      <%= f.text_field :password_confirmation %>
    </div>
    
    <div class="registrations-btn">
      <%= f.submit "新規登録", class: 'btn btn-primary' %>
    </div>
  <% end %>
  </div>
</div>